'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Table_3
    Public Property SATIS As Integer
    Public Property URUN As Integer
    Public Property MUSTERI As Nullable(Of Integer)
    Public Property ADET As Nullable(Of Byte)
    Public Property FIYAT As Nullable(Of Decimal)

End Class
